# fly.toml app configuration file generated for avm on 2024-02-01T10:23:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'avm'
primary_region = 'ams'
console_command = '/code/manage.py shell'

[build]

[deploy]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  auto_stop_machines = 'off'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[mounts]
  source="avm_sqlite"
  destination="/db"