# Generated by Django 2.2.7 on 2019-12-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.IntegerField(default=1)),
                ('guests', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('availableLessons', models.IntegerField(default=0)),
                ('subscriptionType', models.CharField(choices=[('Lezioni', 'Lezioni'), ('Mensile', 'Mensile')], max_length=16)),
                ('subscriptionStart', models.DateField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('lessons', models.ManyToManyField(to='lessons.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='participants',
            field=models.ManyToManyField(to='lessons.Person'),
        ),
    ]
