# Generated by Django 2.2.7 on 2019-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='guests',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='lessons.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subscriptionStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
