# Generated by Django 2.2.7 on 2020-01-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20191229_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='participants',
            field=models.ManyToManyField(blank=True, to='lessons.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='person',
            name='availableLessons',
            field=models.IntegerField(default=0, verbose_name='available lessons'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subscriptionStart',
            field=models.DateField(blank=True, null=True, verbose_name='subscription start'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subscriptionType',
            field=models.CharField(choices=[('Lezioni', 'Lezioni'), ('Mensile', 'Mensile')], max_length=16, verbose_name='subscription type'),
        ),
    ]
