# Generated by Django 3.0.4 on 2020-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200125_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lezione', 'verbose_name_plural': 'Lezioni'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Iscritto', 'verbose_name_plural': 'Iscritti'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cost',
            field=models.IntegerField(default=1, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='guests',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ospiti'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='participants',
            field=models.ManyToManyField(blank=True, to='lessons.Person', verbose_name='Partecipanti'),
        ),
        migrations.AlterField(
            model_name='person',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archiviato'),
        ),
        migrations.AlterField(
            model_name='person',
            name='availableLessons',
            field=models.IntegerField(default=0, verbose_name='Lezioni disponibili'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.Lesson', verbose_name='Lezioni partecipate'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subscriptionStart',
            field=models.DateField(blank=True, null=True, verbose_name='Data inizio abbonamento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subscriptionType',
            field=models.CharField(choices=[('Lezioni', 'Lezioni'), ('Mensile', 'Mensile')], max_length=16, verbose_name='Tipologia abbonamento'),
        ),
    ]
