# Generated by Django 3.0.4 on 2020-03-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200311_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lessons',
        ),
    ]
